
cookies = {
    '加拉尔涂鸦饼干': './img/cookie1.png',
    '旅行者甜甜球': './img/cookie2.png',
    '巧克力飞船饼干': './img/cookie3.png',
    '遥测木薯': './img/cookie4.png',
    '埃里克斯尼鸟食': './img/cookie5.png',
    '绅士脆饼': './img/cookie6.png',
    '无尽森林蛋糕': './img/cookie7.png',
    '香草利刃': './img/cookie8.png',
    '黑巧克力萤光': './img/cookie9.png',
    '厄运饼干': './img/cookie10.png',
    '奇怪饼干': './img/cookie11.png',
    '淡紫丝带曲奇': './img/cookie12.png',
    '交叉火力馒头': './img/cookie13.png',
    '上维燕麦葡萄干曲奇': './img/cookie14.png',
    '乙太冷点': './img/cookie15.png',
    '蓝莓面包': './img/cookie16.png',
    '苦甜饼干': './img/cookie17.png',
    '光尘雪球': './img/cookie18.png',
    '经典黄油曲奇': './img/cookie19.png',
    '星芽薄片': './img/cookie20.png',
    '上维苹果挞': './img/cookie21.png',
}
